//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WTStatistics.Resx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("WTStatistics.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ConsoleHintLabel {
            get {
                return ResourceManager.GetString("ConsoleHintLabel", resourceCulture);
            }
        }
        
        internal static string Winrate {
            get {
                return ResourceManager.GetString("Winrate", resourceCulture);
            }
        }
        
        internal static string EnterNickname {
            get {
                return ResourceManager.GetString("EnterNickname", resourceCulture);
            }
        }
        
        internal static string KillBattleRatio {
            get {
                return ResourceManager.GetString("KillBattleRatio", resourceCulture);
            }
        }
        
        internal static string FavoriteGameModes {
            get {
                return ResourceManager.GetString("FavoriteGameModes", resourceCulture);
            }
        }
        
        internal static string AB {
            get {
                return ResourceManager.GetString("AB", resourceCulture);
            }
        }
        
        internal static string RB {
            get {
                return ResourceManager.GetString("RB", resourceCulture);
            }
        }
        
        internal static string SB {
            get {
                return ResourceManager.GetString("SB", resourceCulture);
            }
        }
        
        internal static string Air {
            get {
                return ResourceManager.GetString("Air", resourceCulture);
            }
        }
        
        internal static string Ground {
            get {
                return ResourceManager.GetString("Ground", resourceCulture);
            }
        }
        
        internal static string Sea {
            get {
                return ResourceManager.GetString("Sea", resourceCulture);
            }
        }
        
        internal static string AirAB {
            get {
                return ResourceManager.GetString("AirAB", resourceCulture);
            }
        }
        
        internal static string AirRB {
            get {
                return ResourceManager.GetString("AirRB", resourceCulture);
            }
        }
        
        internal static string AirSB {
            get {
                return ResourceManager.GetString("AirSB", resourceCulture);
            }
        }
        
        internal static string TankAB {
            get {
                return ResourceManager.GetString("TankAB", resourceCulture);
            }
        }
        
        internal static string TankRB {
            get {
                return ResourceManager.GetString("TankRB", resourceCulture);
            }
        }
        
        internal static string TankSB {
            get {
                return ResourceManager.GetString("TankSB", resourceCulture);
            }
        }
        
        internal static string FleetAB {
            get {
                return ResourceManager.GetString("FleetAB", resourceCulture);
            }
        }
        
        internal static string FleetRB {
            get {
                return ResourceManager.GetString("FleetRB", resourceCulture);
            }
        }
        
        internal static string USA {
            get {
                return ResourceManager.GetString("USA", resourceCulture);
            }
        }
        
        internal static string Germany {
            get {
                return ResourceManager.GetString("Germany", resourceCulture);
            }
        }
        
        internal static string USSR {
            get {
                return ResourceManager.GetString("USSR", resourceCulture);
            }
        }
        
        internal static string Britain {
            get {
                return ResourceManager.GetString("Britain", resourceCulture);
            }
        }
        
        internal static string Japan {
            get {
                return ResourceManager.GetString("Japan", resourceCulture);
            }
        }
        
        internal static string Italy {
            get {
                return ResourceManager.GetString("Italy", resourceCulture);
            }
        }
        
        internal static string France {
            get {
                return ResourceManager.GetString("France", resourceCulture);
            }
        }
        
        internal static string TotalCountOfVehicles {
            get {
                return ResourceManager.GetString("TotalCountOfVehicles", resourceCulture);
            }
        }
        
        internal static string ResearchedVehicles {
            get {
                return ResourceManager.GetString("ResearchedVehicles", resourceCulture);
            }
        }
        
        internal static string Researched {
            get {
                return ResourceManager.GetString("Researched", resourceCulture);
            }
        }
        
        internal static string ExcellentPlayer {
            get {
                return ResourceManager.GetString("ExcellentPlayer", resourceCulture);
            }
        }
        
        internal static string Fighter {
            get {
                return ResourceManager.GetString("Fighter", resourceCulture);
            }
        }
        
        internal static string MediumTanks {
            get {
                return ResourceManager.GetString("MediumTanks", resourceCulture);
            }
        }
        
        internal static string Boats {
            get {
                return ResourceManager.GetString("Boats", resourceCulture);
            }
        }
        
        internal static string SPAA {
            get {
                return ResourceManager.GetString("SPAA", resourceCulture);
            }
        }
        
        internal static string Bomber {
            get {
                return ResourceManager.GetString("Bomber", resourceCulture);
            }
        }
        
        internal static string HintEggDesc {
            get {
                return ResourceManager.GetString("HintEggDesc", resourceCulture);
            }
        }
        
        internal static string HintIconDesc {
            get {
                return ResourceManager.GetString("HintIconDesc", resourceCulture);
            }
        }
        
        internal static string HintClockDesc {
            get {
                return ResourceManager.GetString("HintClockDesc", resourceCulture);
            }
        }
        
        internal static string HintSwordDesc {
            get {
                return ResourceManager.GetString("HintSwordDesc", resourceCulture);
            }
        }
        
        internal static string BadPlayer {
            get {
                return ResourceManager.GetString("BadPlayer", resourceCulture);
            }
        }
        
        internal static string AveragePlayer {
            get {
                return ResourceManager.GetString("AveragePlayer", resourceCulture);
            }
        }
        
        internal static string GoodPlayer {
            get {
                return ResourceManager.GetString("GoodPlayer", resourceCulture);
            }
        }
        
        internal static string OutstandingPlayer {
            get {
                return ResourceManager.GetString("OutstandingPlayer", resourceCulture);
            }
        }
        
        internal static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        internal static string PleaseMakeSureTheInternetIsAvailableAndTryAgain {
            get {
                return ResourceManager.GetString("PleaseMakeSureTheInternetIsAvailableAndTryAgain", resourceCulture);
            }
        }
        
        internal static string IncorrectNickname {
            get {
                return ResourceManager.GetString("IncorrectNickname", resourceCulture);
            }
        }
        
        internal static string NicknameDesc {
            get {
                return ResourceManager.GetString("NicknameDesc", resourceCulture);
            }
        }
        
        internal static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        internal static string SomethingWentWrongNPleaseTryAgainLater {
            get {
                return ResourceManager.GetString("SomethingWentWrongNPleaseTryAgainLater", resourceCulture);
            }
        }
        
        internal static string Attacker {
            get {
                return ResourceManager.GetString("Attacker", resourceCulture);
            }
        }
        
        internal static string HeavyTanks {
            get {
                return ResourceManager.GetString("HeavyTanks", resourceCulture);
            }
        }
        
        internal static string TankDestroyer {
            get {
                return ResourceManager.GetString("TankDestroyer", resourceCulture);
            }
        }
        
        internal static string Barge {
            get {
                return ResourceManager.GetString("Barge", resourceCulture);
            }
        }
        
        internal static string Frigate {
            get {
                return ResourceManager.GetString("Frigate", resourceCulture);
            }
        }
        
        internal static string ShipDestroyer {
            get {
                return ResourceManager.GetString("ShipDestroyer", resourceCulture);
            }
        }
        
        internal static string H {
            get {
                return ResourceManager.GetString("H", resourceCulture);
            }
        }
        
        internal static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        internal static string RateTheApp {
            get {
                return ResourceManager.GetString("RateTheApp", resourceCulture);
            }
        }
        
        internal static string TryOurApps {
            get {
                return ResourceManager.GetString("TryOurApps", resourceCulture);
            }
        }
        
        internal static string DownloadVersus {
            get {
                return ResourceManager.GetString("DownloadVersus", resourceCulture);
            }
        }
        
        internal static string DownloadCharts {
            get {
                return ResourceManager.GetString("DownloadCharts", resourceCulture);
            }
        }
        
        internal static string DownloadWTQuiz {
            get {
                return ResourceManager.GetString("DownloadWTQuiz", resourceCulture);
            }
        }
        
        internal static string DownloadWoTQuiz {
            get {
                return ResourceManager.GetString("DownloadWoTQuiz", resourceCulture);
            }
        }
        
        internal static string ConsoleHint {
            get {
                return ResourceManager.GetString("ConsoleHint", resourceCulture);
            }
        }
        
        internal static string SquadClanTag {
            get {
                return ResourceManager.GetString("SquadClanTag", resourceCulture);
            }
        }
        
        internal static string WinrateHint {
            get {
                return ResourceManager.GetString("WinrateHint", resourceCulture);
            }
        }
        
        internal static string WinrateDesc {
            get {
                return ResourceManager.GetString("WinrateDesc", resourceCulture);
            }
        }
        
        internal static string Efficiency {
            get {
                return ResourceManager.GetString("Efficiency", resourceCulture);
            }
        }
        
        internal static string EfficiencyDesc {
            get {
                return ResourceManager.GetString("EfficiencyDesc", resourceCulture);
            }
        }
        
        internal static string FavoriteMode {
            get {
                return ResourceManager.GetString("FavoriteMode", resourceCulture);
            }
        }
        
        internal static string FavoriteModeDesc {
            get {
                return ResourceManager.GetString("FavoriteModeDesc", resourceCulture);
            }
        }
        
        internal static string FavoriteTypeOfVehicle {
            get {
                return ResourceManager.GetString("FavoriteTypeOfVehicle", resourceCulture);
            }
        }
        
        internal static string FavoriteTypeOfVehicleDesc {
            get {
                return ResourceManager.GetString("FavoriteTypeOfVehicleDesc", resourceCulture);
            }
        }
        
        internal static string TotalNumberOfResearchedVehicles {
            get {
                return ResourceManager.GetString("TotalNumberOfResearchedVehicles", resourceCulture);
            }
        }
        
        internal static string TotalNumberOfResearchedVehiclesDesc {
            get {
                return ResourceManager.GetString("TotalNumberOfResearchedVehiclesDesc", resourceCulture);
            }
        }
        
        internal static string TryOurGames {
            get {
                return ResourceManager.GetString("TryOurGames", resourceCulture);
            }
        }
        
        internal static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        internal static string Hints {
            get {
                return ResourceManager.GetString("Hints", resourceCulture);
            }
        }
        
        internal static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        internal static string PlayerAB {
            get {
                return ResourceManager.GetString("PlayerAB", resourceCulture);
            }
        }
        
        internal static string PlayerRB {
            get {
                return ResourceManager.GetString("PlayerRB", resourceCulture);
            }
        }
        
        internal static string PlayerSB {
            get {
                return ResourceManager.GetString("PlayerSB", resourceCulture);
            }
        }
        
        internal static string PlayerUSA {
            get {
                return ResourceManager.GetString("PlayerUSA", resourceCulture);
            }
        }
        
        internal static string PlayerGermany {
            get {
                return ResourceManager.GetString("PlayerGermany", resourceCulture);
            }
        }
        
        internal static string PlayerUssr {
            get {
                return ResourceManager.GetString("PlayerUssr", resourceCulture);
            }
        }
        
        internal static string PlayerBritain {
            get {
                return ResourceManager.GetString("PlayerBritain", resourceCulture);
            }
        }
        
        internal static string PlayerJapan {
            get {
                return ResourceManager.GetString("PlayerJapan", resourceCulture);
            }
        }
        
        internal static string PlayerItaly {
            get {
                return ResourceManager.GetString("PlayerItaly", resourceCulture);
            }
        }
        
        internal static string PlayerFrance {
            get {
                return ResourceManager.GetString("PlayerFrance", resourceCulture);
            }
        }
        
        internal static string PlayerChina {
            get {
                return ResourceManager.GetString("PlayerChina", resourceCulture);
            }
        }
        
        internal static string PlayerSweden {
            get {
                return ResourceManager.GetString("PlayerSweden", resourceCulture);
            }
        }
        
        internal static string WTMapGuide {
            get {
                return ResourceManager.GetString("WTMapGuide", resourceCulture);
            }
        }
        
        internal static string FavoriteTypesOfVehicles {
            get {
                return ResourceManager.GetString("FavoriteTypesOfVehicles", resourceCulture);
            }
        }
        
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        internal static string CheckThisCoolApp {
            get {
                return ResourceManager.GetString("CheckThisCoolApp", resourceCulture);
            }
        }
        
        internal static string ShareWithFriends {
            get {
                return ResourceManager.GetString("ShareWithFriends", resourceCulture);
            }
        }
        
        internal static string WTSkillMeterAboutText {
            get {
                return ResourceManager.GetString("WTSkillMeterAboutText", resourceCulture);
            }
        }
        
        internal static string WTSkillMeterAboutTextIOS {
            get {
                return ResourceManager.GetString("WTSkillMeterAboutTextIOS", resourceCulture);
            }
        }
        
        internal static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        internal static string AppForAnalyzeWarVehicle {
            get {
                return ResourceManager.GetString("AppForAnalyzeWarVehicle", resourceCulture);
            }
        }
        
        internal static string ReportABug {
            get {
                return ResourceManager.GetString("ReportABug", resourceCulture);
            }
        }
        
        internal static string FollowTheNewsAskQuestion {
            get {
                return ResourceManager.GetString("FollowTheNewsAskQuestion", resourceCulture);
            }
        }
        
        internal static string AppForVehiclesComparison {
            get {
                return ResourceManager.GetString("AppForVehiclesComparison", resourceCulture);
            }
        }
        
        internal static string TriviaGameWithWarThunderVehicles {
            get {
                return ResourceManager.GetString("TriviaGameWithWarThunderVehicles", resourceCulture);
            }
        }
        
        internal static string TriviaGameWithWorldOfTanksVehicles {
            get {
                return ResourceManager.GetString("TriviaGameWithWorldOfTanksVehicles", resourceCulture);
            }
        }
    }
}
