//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WTStatistics.Resx {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WTStatistics.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AB.
        /// </summary>
        internal static string AB {
            get {
                return ResourceManager.GetString("AB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Air.
        /// </summary>
        internal static string Air {
            get {
                return ResourceManager.GetString("Air", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Air AB.
        /// </summary>
        internal static string AirAB {
            get {
                return ResourceManager.GetString("AirAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Air RB.
        /// </summary>
        internal static string AirRB {
            get {
                return ResourceManager.GetString("AirRB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Air SB.
        /// </summary>
        internal static string AirSB {
            get {
                return ResourceManager.GetString("AirSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attacker.
        /// </summary>
        internal static string Attacker {
            get {
                return ResourceManager.GetString("Attacker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Average player.
        /// </summary>
        internal static string AveragePlayer {
            get {
                return ResourceManager.GetString("AveragePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bad player.
        /// </summary>
        internal static string BadPlayer {
            get {
                return ResourceManager.GetString("BadPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Barge.
        /// </summary>
        internal static string Barge {
            get {
                return ResourceManager.GetString("Barge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Boats.
        /// </summary>
        internal static string Boats {
            get {
                return ResourceManager.GetString("Boats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bomber.
        /// </summary>
        internal static string Bomber {
            get {
                return ResourceManager.GetString("Bomber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Britain.
        /// </summary>
        internal static string Britain {
            get {
                return ResourceManager.GetString("Britain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на If you have PS account, add @psn to end of your nickname. If you have Xbox account, add @live to end of your nickname. For example Player1@psn or Player1@live.
        /// </summary>
        internal static string ConsoleHint {
            get {
                return ResourceManager.GetString("ConsoleHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hint for Xbox and PS players.
        /// </summary>
        internal static string ConsoleHintLabel {
            get {
                return ResourceManager.GetString("ConsoleHintLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Contact us:.
        /// </summary>
        internal static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WT Analyzer.
        /// </summary>
        internal static string DownloadCharts {
            get {
                return ResourceManager.GetString("DownloadCharts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WT Versus.
        /// </summary>
        internal static string DownloadVersus {
            get {
                return ResourceManager.GetString("DownloadVersus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WoT Quiz.
        /// </summary>
        internal static string DownloadWoTQuiz {
            get {
                return ResourceManager.GetString("DownloadWoTQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WT Quiz.
        /// </summary>
        internal static string DownloadWTQuiz {
            get {
                return ResourceManager.GetString("DownloadWTQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Efficiency.
        /// </summary>
        internal static string Efficiency {
            get {
                return ResourceManager.GetString("Efficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на kill to battle ratio. Don&apos;t confuse battle (1 respawn) and match (whole battle with many respawns).
        /// </summary>
        internal static string EfficiencyDesc {
            get {
                return ResourceManager.GetString("EfficiencyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter nickname.
        /// </summary>
        internal static string EnterNickname {
            get {
                return ResourceManager.GetString("EnterNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Excellent player.
        /// </summary>
        internal static string ExcellentPlayer {
            get {
                return ResourceManager.GetString("ExcellentPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Favorite game modes.
        /// </summary>
        internal static string FavoriteGameModes {
            get {
                return ResourceManager.GetString("FavoriteGameModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Favorite mode.
        /// </summary>
        internal static string FavoriteMode {
            get {
                return ResourceManager.GetString("FavoriteMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на the number of battles for each game mode.
        /// </summary>
        internal static string FavoriteModeDesc {
            get {
                return ResourceManager.GetString("FavoriteModeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Favorite type of vehicle.
        /// </summary>
        internal static string FavoriteTypeOfVehicle {
            get {
                return ResourceManager.GetString("FavoriteTypeOfVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на the number of battles for each type of vehicle.
        /// </summary>
        internal static string FavoriteTypeOfVehicleDesc {
            get {
                return ResourceManager.GetString("FavoriteTypeOfVehicleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Feedback.
        /// </summary>
        internal static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fighter.
        /// </summary>
        internal static string Fighter {
            get {
                return ResourceManager.GetString("Fighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fleet AB.
        /// </summary>
        internal static string FleetAB {
            get {
                return ResourceManager.GetString("FleetAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fleet RB.
        /// </summary>
        internal static string FleetRB {
            get {
                return ResourceManager.GetString("FleetRB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на France.
        /// </summary>
        internal static string France {
            get {
                return ResourceManager.GetString("France", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Frigate.
        /// </summary>
        internal static string Frigate {
            get {
                return ResourceManager.GetString("Frigate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Germany.
        /// </summary>
        internal static string Germany {
            get {
                return ResourceManager.GetString("Germany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Good player.
        /// </summary>
        internal static string GoodPlayer {
            get {
                return ResourceManager.GetString("GoodPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ground.
        /// </summary>
        internal static string Ground {
            get {
                return ResourceManager.GetString("Ground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  h.
        /// </summary>
        internal static string H {
            get {
                return ResourceManager.GetString("H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Heavy tanks.
        /// </summary>
        internal static string HeavyTanks {
            get {
                return ResourceManager.GetString("HeavyTanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на total play time in all modes.
        /// </summary>
        internal static string HintClockDesc {
            get {
                return ResourceManager.GetString("HintClockDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на account registration date.
        /// </summary>
        internal static string HintEggDesc {
            get {
                return ResourceManager.GetString("HintEggDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на total number of earned silver lions.
        /// </summary>
        internal static string HintIconDesc {
            get {
                return ResourceManager.GetString("HintIconDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hints.
        /// </summary>
        internal static string Hints {
            get {
                return ResourceManager.GetString("Hints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на total number of completed mission (match).
        /// </summary>
        internal static string HintSwordDesc {
            get {
                return ResourceManager.GetString("HintSwordDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Incorrect nickname.
        /// </summary>
        internal static string IncorrectNickname {
            get {
                return ResourceManager.GetString("IncorrectNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Italy.
        /// </summary>
        internal static string Italy {
            get {
                return ResourceManager.GetString("Italy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Japan.
        /// </summary>
        internal static string Japan {
            get {
                return ResourceManager.GetString("Japan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Kill/battle ratio.
        /// </summary>
        internal static string KillBattleRatio {
            get {
                return ResourceManager.GetString("KillBattleRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Medium tanks.
        /// </summary>
        internal static string MediumTanks {
            get {
                return ResourceManager.GetString("MediumTanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Nickname doesn&apos;t exist. Please enter correct nickname.
        /// </summary>
        internal static string NicknameDesc {
            get {
                return ResourceManager.GetString("NicknameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No Internet.
        /// </summary>
        internal static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Outstanding player.
        /// </summary>
        internal static string OutstandingPlayer {
            get {
                return ResourceManager.GetString("OutstandingPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ab.
        /// </summary>
        internal static string PlayerAB {
            get {
                return ResourceManager.GetString("PlayerAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на britain.
        /// </summary>
        internal static string PlayerBritain {
            get {
                return ResourceManager.GetString("PlayerBritain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на china.
        /// </summary>
        internal static string PlayerChina {
            get {
                return ResourceManager.GetString("PlayerChina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на france.
        /// </summary>
        internal static string PlayerFrance {
            get {
                return ResourceManager.GetString("PlayerFrance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на germany.
        /// </summary>
        internal static string PlayerGermany {
            get {
                return ResourceManager.GetString("PlayerGermany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на italy.
        /// </summary>
        internal static string PlayerItaly {
            get {
                return ResourceManager.GetString("PlayerItaly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на japan.
        /// </summary>
        internal static string PlayerJapan {
            get {
                return ResourceManager.GetString("PlayerJapan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на rb.
        /// </summary>
        internal static string PlayerRB {
            get {
                return ResourceManager.GetString("PlayerRB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на sb.
        /// </summary>
        internal static string PlayerSB {
            get {
                return ResourceManager.GetString("PlayerSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на sweden.
        /// </summary>
        internal static string PlayerSweden {
            get {
                return ResourceManager.GetString("PlayerSweden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на usa.
        /// </summary>
        internal static string PlayerUSA {
            get {
                return ResourceManager.GetString("PlayerUSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ussr.
        /// </summary>
        internal static string PlayerUssr {
            get {
                return ResourceManager.GetString("PlayerUssr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please make sure the internet is available and try again.
        /// </summary>
        internal static string PleaseMakeSureTheInternetIsAvailableAndTryAgain {
            get {
                return ResourceManager.GetString("PleaseMakeSureTheInternetIsAvailableAndTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rate this app:.
        /// </summary>
        internal static string RateUsInGooglePlay {
            get {
                return ResourceManager.GetString("RateUsInGooglePlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RB.
        /// </summary>
        internal static string RB {
            get {
                return ResourceManager.GetString("RB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Researched.
        /// </summary>
        internal static string Researched {
            get {
                return ResourceManager.GetString("Researched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Researched vehicles.
        /// </summary>
        internal static string ResearchedVehicles {
            get {
                return ResourceManager.GetString("ResearchedVehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SB.
        /// </summary>
        internal static string SB {
            get {
                return ResourceManager.GetString("SB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sea.
        /// </summary>
        internal static string Sea {
            get {
                return ResourceManager.GetString("Sea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ship destroyer.
        /// </summary>
        internal static string ShipDestroyer {
            get {
                return ResourceManager.GetString("ShipDestroyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Something went wrong. Please try again later.
        /// </summary>
        internal static string SomethingWentWrongNPleaseTryAgainLater {
            get {
                return ResourceManager.GetString("SomethingWentWrongNPleaseTryAgainLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SPAA.
        /// </summary>
        internal static string SPAA {
            get {
                return ResourceManager.GetString("SPAA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на squad clan tag.
        /// </summary>
        internal static string SquadClanTag {
            get {
                return ResourceManager.GetString("SquadClanTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Statistics.
        /// </summary>
        internal static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tank AB.
        /// </summary>
        internal static string TankAB {
            get {
                return ResourceManager.GetString("TankAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tank destroyer.
        /// </summary>
        internal static string TankDestroyer {
            get {
                return ResourceManager.GetString("TankDestroyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tank RB.
        /// </summary>
        internal static string TankRB {
            get {
                return ResourceManager.GetString("TankRB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tank SB.
        /// </summary>
        internal static string TankSB {
            get {
                return ResourceManager.GetString("TankSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Timeout.
        /// </summary>
        internal static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total count.
        /// </summary>
        internal static string TotalCountOfVehicles {
            get {
                return ResourceManager.GetString("TotalCountOfVehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total number of researched vehicles.
        /// </summary>
        internal static string TotalNumberOfResearchedVehicles {
            get {
                return ResourceManager.GetString("TotalNumberOfResearchedVehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на the number of researched vehicles for each game nation.
        /// </summary>
        internal static string TotalNumberOfResearchedVehiclesDesc {
            get {
                return ResourceManager.GetString("TotalNumberOfResearchedVehiclesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Try our apps:.
        /// </summary>
        internal static string TryOurApps {
            get {
                return ResourceManager.GetString("TryOurApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Try our games:.
        /// </summary>
        internal static string TryOurGames {
            get {
                return ResourceManager.GetString("TryOurGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на USA.
        /// </summary>
        internal static string USA {
            get {
                return ResourceManager.GetString("USA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на USSR.
        /// </summary>
        internal static string USSR {
            get {
                return ResourceManager.GetString("USSR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Winrate (AB/RB/SB).
        /// </summary>
        internal static string Winrate {
            get {
                return ResourceManager.GetString("Winrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на just win rate for each mode.
        /// </summary>
        internal static string WinrateDesc {
            get {
                return ResourceManager.GetString("WinrateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Winrate.
        /// </summary>
        internal static string WinrateHint {
            get {
                return ResourceManager.GetString("WinrateHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на In development.
        /// </summary>
        internal static string WTMapGuide {
            get {
                return ResourceManager.GetString("WTMapGuide", resourceCulture);
            }
        }
    }
}
